import type { Plugin } from "vue";

import {
  ImsButton,
  ImsPopconfirmButton,
  ImsJsonViewer,
  ImsSelect,
  ImsBreadCrumb,
  ImsCascader,
  ImsNavMenu,
  ImsModal,
  ImsForm,
  ImsCurd,
  ImsIconPicker,
  ImsTable,
  ImsSpin,
  ImsSectionTitle,
  ImsFormDivider,
  ImsUploader,
  ImsTagSelect,
  ImsFormTable,
  ImsOverlayScrollbar,
  ImsEditor,
  ImsVtable,
  ImsCustomizationOptions,
  ImsGridLayout,
} from "@imsjs/ims-ui-components";

export default [
  ImsButton,
  ImsPopconfirmButton,
  ImsJsonViewer,
  ImsSelect,
  ImsTagSelect,
  ImsBreadCrumb,
  ImsCascader,
  ImsNavMenu,
  ImsModal,
  ImsForm,
  ImsCurd,
  ImsIconPicker,
  ImsTable,
  ImsSpin,
  ImsSectionTitle,
  ImsFormDivider,
  ImsUploader,
  ImsFormTable,
  ImsOverlayScrollbar,
  ImsEditor,
  ImsVtable,
  ImsCustomizationOptions,
  ImsGridLayout,
] as Plugin[];
